apiVersion: v1
kind: Secret
metadata:
  name: yc-creds
type: Opaque
data:
  credentials: {{ .Values.providerJetYC.creds | b64enc }}
---
apiVersion: yandex-cloud.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: yc-creds
      namespace: {{ .Release.Namespace }}
      key: credentials
