apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: registry-pusher
spec:
  deletionPolicy: Orphan
  forProvider:
    name: registry-pusher
    folderIdRef:
      name: default
---
apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: registry-pusher
spec:
  deletionPolicy: Orphan
  forProvider:
    serviceAccountsRef:
      - name: registry-pusher
    role: container-registry.images.pusher
    folderIdRef:
      name: default
